language: php

php:
    - 8.0
    - 8.1
    - hhvm

matrix:
    allow_failures:
        - php: hhvm

before_script:
    - composer self-update
    - composer install --no-interaction --prefer-source

script:
    - phpunit
